version: '3.5'

volumes:
  fleet-logs:
  fleet-db:

networks:
  fleet:
    name: fleet

services:
  #######################################
  # MYSQL
  #######################################
  fleet-mysql:
    image: mysql:${MYSQL_VERSION:-5.7}
    platform: linux/x86_64
    command: 'mysqld --datadir=/tmp/data --event-scheduler=ON'
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - fleet-db:/var/lib/mysql
    networks:
      - fleet
    ports:
      - "3308:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      interval: 1s
      retries: 120
  #######################################
  # REDIS
  #######################################
  fleet-redis:
    image: redis:${REDIS_VERSION:-6}
    restart: unless-stopped
    networks:
      - fleet
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
  #######################################
  # FLEET-CORE
  # Backend Fleet server for clients
  #######################################
  fleet-core:
    image: fleetdm/fleet:${FLEET_VERSION:-latest}
    platform: linux/x86_64
    command: sh -c "/usr/bin/fleet prepare db --no-prompt && /usr/bin/fleet serve"
    restart: unless-stopped
    env_file:
      .config/fleet_conf.env
    environment:
      FLEET_SERVER_CERT: ${FLEET_SERVER_CERT}
      FLEET_SERVER_KEY: ${FLEET_SERVER_KEY}
      FLEET_LICENSE_KEY: ${FLEET_LICENSE_KEY}
      FLEET_MYSQL_DATABASE: ${MYSQL_DATABASE}
      FLEET_MYSQL_USERNAME: ${MYSQL_USER}
      FLEET_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    depends_on:
      - fleet-mysql
      - fleet-redis
    volumes:
      - fleet-logs:/var/log/osquery
      - ${FLEET_SERVER_CERT}:${FLEET_SERVER_CERT}
      - ${FLEET_SERVER_KEY}:${FLEET_SERVER_KEY}
    networks:
      fleet:
        aliases:
          - host.docker.internal
          - localhost
    ports:
      - "8080:8080"